# Generated by Django 4.0.4 on 2022-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
