# Generated by Django 4.0.4 on 2022-05-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_field_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='clients',
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(to='hr.tag'),
        ),
    ]
